name: 喜马拉雅极速版

on:
    workflow_dispatch:
    schedule:
        - cron: "2,32 * * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: xmly_speed

jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Checkout
              run: |

            - name: "Set up Python"
              uses: actions/setup-python@v1
              with:
                  python-version: 3.7
            - name: 'Install requests'
              run: |
                pip install requests
                pip install rsa
                npm install util
            - name: "安装依赖包"
              run: pip install -r ./requirements.txt
                   git clone https://github.com/QingAnLe/YiYu.git ~/js
                   git checkout JD-hundun
            - name: "运行 喜马拉雅极速版"
              run: python3 quanx/xmly_speed.py
              env:
                  XMLY_SPEED_COOKIE: ${{ secrets.XMLY_SPEED_COOKIE }}  #必须 cookie 多账号 \n 分割
                  AUTO_TAKE_OUT: ${{ secrets.AUTO_TAKE_OUT }}  #非必须 是否自动提现支付宝20
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
                  TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人userId
                  SYNCURL: https://raw.githubusercontent.com/whyour/hundun/master/quanx/xmly_speed.py
