name: 中青看点

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 5,23 * * *'
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: 'Install requests'
        run: pip install requests

      - name: 'run 中青看点'
        run: python3 Task/youth.py
        env:
            YOUTH_HEADER1: ${{ secrets.YOUTH_HEADER1 }}  #必须 账号1 body1
            YOUTH_READBODY1: ${{ secrets.YOUTH_READBODY1 }}  #必须 账号1 body1
            YOUTH_READTIMEBODY1: ${{ secrets.YOUTH_READTIMEBODY1 }}  #必须 账号1 body1
            YOUTH_WITHDRAWBODY1: ${{ secrets.YOUTH_WITHDRAWBODY1 }}  #非必须 账号1提现 body1
            YOUTH_SHAREBODY1: ${{ secrets.YOUTH_SHAREBODY1 }}  #必须 账号1 body1
            YOUTH_STARTBODY1: ${{ secrets.YOUTH_STARTBODY1 }}  #必须 账号1 body1
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}  #非必须 tg机器人token
            TG_USER_ID: ${{ secrets.TG_USER_ID }}  #非必须 tg机器人id
