name: 多多爱运动
on:
  workflow_dispatch:
  schedule:
     - cron: '6 9 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest       
    steps:
      
      - name: Checkout
        run: |
          git clone https://github.com/QingAnLe/YiYu.git ~/js
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/js
          npm install got
          npm install cron
          npm install request
          npm install tough-cookie
      - name: '【多多爱运动】'
        run: |
          cd ~/js   
          node Task/ddayd.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
