on:
  workflow_dispatch:
  schedule:
     - cron: '10 5-15 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/adw2s/Action.git ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update

      - name: '运行 【番茄看看】'
        if: env.fqkkurl
        run: |
          cd ~/Scripts
          node Task/11fqkk.js
        env:
          fqkkurl: ${{ secrets.fqkkurl }}
          fqkkhd: ${{ secrets.fqkkhd }}
          fqkkck: ${{ secrets.fqkkck }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
