# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 27jdtq(简单天气)

on:
  workflow_dispatch:
  schedule:
     - cron: '10 0-16/3 * * *'
  watch:
    types: started
#env:
  #TZ: Asia/Shanghai

jobs:
  build1:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone ${{ secrets.GIT_CLONE_URL }} ~/Scripts
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          cd ~/Scripts
          npm install -g npm
          npm update
      - name: '运行 【简单天气】'
        run: |
          cd ~/Scripts
          node Task/27jdtq.js
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets.TG_USER_ID }}
