name: 腾讯自选股

on:
  workflow_dispatch:
  schedule:
     - cron: '0 8 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/QingAnLe/YiYu ~/js
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env. USERHEADER
        run: |
          cd ~/js
          git checkout main
          npm install
          curl ipinfo.io/iboxpayCOOKIE.js
      - name: '运行 【腾讯多选股】'
        if: env.USERHEADER
        run: |
          cd ~/js
          node Task/txstockCOOKIE.js
        env:
          
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: ${{ secrets. TG_USER_ID }}
