name: 春风赚

on:
  workflow_dispatch:
  schedule:
     - cron: '0 8 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      USERHEADER: ${{ secrets.TXS_USERHEADER }}
      USERKEY: ${{ secrets.TXS_USERKEY }}
      CASHHEADER: ${{ secrets.TXS_CASHHEADER }}
      SIGNHEADER: ${{ secrets.TXS_SIGNHEADER }}
      SIGNKEY: ${{ secrets.TXS_SIGNKEY }}
      TASKHEADER: ${{ secrets.TXS_TASKHEADER }}
      TASKKEY: ${{ secrets.TXS_TASKKEY }}
      WXTASKKEY: ${{ secrets.TXS_WXTASKKEY }}
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/QingAnLe/YiYu ~/js
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        if: env.CFZURL
        run: |
          cd ~/js
          git checkout main
          npm install
      - name: '运行 【腾讯多选股】'
        if: env.USERHEADER
        run: |
          cd ~/js
          node Task/.js
        env:
          
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_USER_ID: $
